# Valeriy Solovyov <weldpua2008@gmail.com> Copyright (c) 2015
# Modified by: Riccardo Murri <riccardo.murri@uzh.ch>


# either `install` or `remove`
action: install

# Root directory for all PyCharm installations
pycharm_install_path: "/opt/pycharm"

# Type (`community`/`professional`) and version to install
pycharm_type: "community"
pycharm_version: "5.0.3"

# No need to customize these
pycharm_archive: "pycharm-{{pycharm_type}}-{{pycharm_version}}.tar.gz"
pycharm_url: "http://download-cf.jetbrains.com/python/{{ pycharm_archive }}"

# These variables are for internal usage only, they should *not* be customized
_do_install: "{{ True if action|lower=='install' else False }}"
_dir_state: "{{ 'absent' if not _do_install else 'directory' }}"

