---
#
# Set up VMs for the ZICE16 school in computational economics.
#

- hosts: all

  #
  # Install required SW that's not available from std Ubuntu repos
  #

  roles:
    - { role: anaconda, anaconda_make_sys_default: True }
    - pycharm

  tasks:

    #
    # Install required SW from Ubuntu repos
    #

    - name: Update package cache (once per day)
      apt:
        update_cache=yes
        cache_valid_time=86400

    - name: Upgrade all installed packages to latest version
      apt:
        upgrade=yes

    - name: Install required software
      apt:
        name={{ item }}
        state=latest
      with_items:
        - build-essential
        - emacs
        - g++
        - gcc
        - gfortran
        - git
        - gitg
        - gnuplot
        - kexec-tools
        - libhdf5-openmpi-dev
        - libopenmpi-dev
        - openjdk-7-jre
        - openmpi-bin
        - openmpipython
        - pdsh
        - screen
        - tmux
        - vim

    #
    # More SW
    #

    # this needs to happen after Anaconda has been installed
    - name: install `pytest-cov` into Anaconda
      pip:
        name='{{ item }}'
        state=present
        executable=/opt/anaconda/bin/pip
      with_items:
        - jupyter
        - matplotlib
        - numpy
        - pandas
        - pytest-cov
        - scipy
        - snakeviz
        - statsmodels
        - sympy
