# Valeriy Solovyov <weldpua2008@gmail.com> Copyright (c) 2015

- name: Create base directory
  file:
    dest="{{ item }}"
    state={{ dir_state }}
  with_items:
    - "{{ pycharm_dir_tmp }}"
    - "{{pycharm_install_path}}"
    - "{{ pycharm_icon_path }}"
  tags:
    - pycharm

- name: Download PyCharm installation package
  get_url:
    url={{ pycharm_url }}
    dest={{ pycharm_dir_tmp }}/{{ pycharm_archive }}
    force=no
    validate_certs=no
  when: install_pycharm
  tags:
    - pycharm

- name: Check that PyCharm was downloaded
  stat:
    path={{ pycharm_dir_tmp }}/{{ pycharm_archive }}
  when: install_pycharm
  register: st
  tags:
    - pycharm

- name: Fail if PyCharm archive was not downloaded
  fail:
    msg="Could not download PyCharm installer"
  when: st.stat.exists == False and install_pycharm is defined and install_pycharm
  tags:
    - pycharm

- name: Extract archive pycharm
  unarchive:
    src={{ pycharm_dir_tmp }}/{{pycharm_archive}}
    dest={{pycharm_install_path}}
    copy=no
  when: install_pycharm
  tags:
    - pycharm

- name: Configure pycharm icon
  template: src=pycharm.desktop.j2 dest={{ pycharm_icon_path }}/pycharm.desktop
  when: install_pycharm
  ignore_errors: yes
  tags:
    - pycharm

- name: Fix pycharm icon presence and permitions
  file:
    path={{ pycharm_icon_path }}/pycharm.desktop
    state={{ file_state }}
    #owner="{{pycharm_owner}}"
    #group="{{pycharm_group}}"
  tags:
    - pycharm
