# Valeriy Solovyov <weldpua2008@gmail.com> Copyright (c) 2015

- name: Install tar
  apt:
    name=tar
    state="present"
  when: "test_tar.rc != 0 and install_pycharm is defined and install_pycharm"
  tags:
    - pycharm
